enc:
  size: [6000, 6000] # [10000, 10000] #
  origin: [ 497000, 5380000 ] #
  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  crs: "UTM10N"
  S57_layers:
    "TSSLPT": "#8B0000" # extra layer (traffic separation scheme with color we want to display it in)
  resources: [ "data/db/US5WA42M" ] # Looks like there are no data in it


display:
  colorbar: False
  dark_mode: False
  fullscreen: False
  controls: True
  resolution: 640
  anchor: "center"
  dpi: 96

